name: Scrape Job Expo

on:
  # 매일 아침 9시에 자동 실행
  schedule:
    - cron: '*/1 * * * *'
  # 수동 실행도 가능
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver xvfb

      - name: Run Scrape Script
        run: |
          Xvfb :99 -ac -screen 0 1920x1080x16 &
          export DISPLAY=:99
          python main.py

      - name: Upload CSV Result
        uses: actions/upload-artifact@v4
        with:
          name: job_expo_data
          path: job_expo.csv
